### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lambtron** [lambtron/meerkash-process#1]
- [ ] pull from jobs queue? need to do research first.
- [ ] venmo.js—abstraction to post charge/payment (https://developer.venmo.com/docs/endpoints/payments)
- [ ] remove dupes (probably based on tweet ID)?
- [ ] parse tweet

**Comment by lambtron** [comment]
- [ ] make sure it works!!!
